# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
